openapi: 3.0.0
info:
  title: Solinca Notification API
  description: API to sent notification when favorite classes are available at Solinca's clubs
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://solinca-notif-portal-apis.herokuapp.com
    description: Production serve
paths:
  /api/v1/user/signin:
    post:
      summary: User login
      description: This API authenticates the user according to the username and password
      requestBody:
        required: true
        description: login body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':   
          description: An object containing user information and auth token
          content:
            application/json:
              schema: 
                type: objects
                  properties:
                  username:
                    type: string
                    description: The username
                    example: janedoe
                  userId:
                    type: string
                    description: The user's ID
                    example: 5354bj646665
                  token:
                    type: string
                    description: The user's authorization token
                    example: ewrewte9tegfewytreyrurt98ryrutyiyrootp
components:
  schemas:
    UserLogin:
      type: object
      properties:
        username:
          type: string
          description: The username
          example: janedoe
        password:
          type: string
          description: The user's password.
          example: admin1234
